import type { FastifyRequest } from 'fastify';
import type { ICommand } from '../../../shared/cqrs/index.js';
import type { UserWithoutPassword } from './register-user.command.js';

/**
 * Result when login succeeds without 2FA
 */
export interface LoginSuccessResult {
  user: UserWithoutPassword;
  sessionId: string;
}

/**
 * Result when 2FA verification is required
 * Note: tempToken is generated by the route layer, not the handler
 */
export interface TwoFactorRequiredResult {
  requiresTwoFactor: true;
  userId: string;
}

/**
 * Union result type for login command
 */
export type LoginResult = LoginSuccessResult | TwoFactorRequiredResult;

/**
 * Command to authenticate a user with email and password.
 *
 * Returns either:
 * - { user, sessionId } on successful login
 * - { requiresTwoFactor: true, userId } when 2FA is needed (route layer generates tempToken)
 */
export class LoginUserCommand implements ICommand<LoginResult> {
  readonly __brand = 'command' as const;
  declare readonly __resultType: LoginResult;

  constructor(
    /** User's email address */
    public readonly email: string,
    /** User's password */
    public readonly password: string,
    /** Fastify request for session metadata (device info, IP) */
    public readonly request: FastifyRequest,
    /** Whether the device is already trusted (has valid session with trustedUntil) */
    public readonly isDeviceTrusted: boolean
  ) {}
}
