// This file is auto-generated by Lingx CLI
// Do not edit manually. Run 'lingx types' to regenerate.

import '@lingx/sdk-nextjs';

declare module '@lingx/sdk-nextjs' {
  /**
   * Generated translation resources.
   * This interface is merged with the SDK's TranslationResources.
   */
  interface TranslationResources {
    /**
     * Root translation keys (no namespace).
     * Generated from source locale translations.
     */
    keys:
      | never;
  }

  /**
   * Namespace-specific translation keys.
   * Each namespace maps to its available keys.
   *
   * Usage: tKey('key', 'namespace')
   */
  interface NamespaceKeys {
    // No namespaces defined
  }

  /**
   * ICU parameter types for translation keys that require parameters.
   * Keys not listed here don't require parameters.
   */
  interface TranslationParams {
    // No keys with parameters
  }
}
